repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check code formatting using rustfmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Lint code using cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
