# Stable flags
edition = "2021"
newline_style = "Unix"
tab_spaces = 4

# Nightly flags
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
unstable_features = true
wrap_comments = true
