name: PR Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install repository Rust toolchain
        run: rustup show

      - name: Install cross
        run: cargo install cross

      - name: Install GUI system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: gui/package-lock.json

      - name: Install Yarn
        run: sudo npm install -g yarn

      - name: Install GUI dependencies
        working-directory: ./gui
        run: |
          npm install
          npm run install:platform

      - name: Build flight computer
        run: cargo build -p flight-computer --release

      - name: Build SAM
        working-directory: ./sam
        run: cross build --target armv7-unknown-linux-gnueabihf

      - name: Build BMS
        working-directory: ./bms
        run: cross build --target armv7-unknown-linux-gnueabihf

      - name: Build common
        run: |
          cargo build -p common --release
          cargo build -p common -F sequences --release

      - name: Build servo
        run: cargo build -p servo --release

      - name: Build ads114s06
        run: cargo build -p ads114s06 --release

      - name: Build imu
        run: cargo build -p imu --release

      - name: Build imu-testing
        run: cargo build -p imu-testing --release

      - name: Build lis2mdl
        run: cargo build -p lis2mdl --release

      - name: Build magnetometer-testing
        run: cargo build -p magnetometer-testing --release

      - name: Build ms5611
        run: cargo build -p ms5611 --release

      - name: Build zedf9p04b
        run: cargo build -p zedf9p04b --release

      - name: Build reco
        run: cargo build -p reco --release

      - name: Build GUI
        working-directory: ./gui
        run: npm run tauri build
